print ("╔════════════════════════════╗")
print ("║       cizimler             ║")
print ("╠════════════════════════════╣")
print ("║  1- düz cizgiler           ║")
print ("║  2- yamuk cizgiler         ║")
print ("║  3- capraz cizgiler        ║")
print ("║  4- paralel cizgiler       ║")
print ("║  5- çıkış                  ║")
print ("╚════════════════════════════╝")