print ("╔════════════════════════════╗")
print ("║       Geziler              ║")
print ("╠════════════════════════════╣")
print ("║  1- planlanan geziler      ║")
print ("║  2- gidilecek yerler       ║")
print ("║  3- gidilen yerler         ║")
print ("║  4- gidilmeyecek yerler    ║")
print ("║  5- çıkış                  ║")
print ("╚════════════════════════════╝")