print ("╔════════════════════════════╗")
print ("║       Hesap Makinesi       ║")
print ("╠════════════════════════════╣")
print ("║  1- İki sayıyı topla       ║")
print ("║  2- kare alanı hesaplama   ║")
print ("║  3- iki sayıyı çarp        ║")
print ("║  4- bölme işlemi           ║")
print ("║  5- çıkış                  ║")
print ("╚════════════════════════════╝")