print ("╔════════════════════════════╗")
print ("║       Oyunlar              ║")
print ("╠════════════════════════════╣")
print ("║  1- oyunda puan topla      ║")
print ("║  2- oyun bölümleri yapma   ║")
print ("║  3- geçilen bölümler       ║")
print ("║  4- kaybedilen bölümler    ║")
print ("║  5- çıkış                  ║")
print ("╚════════════════════════════╝")